import { ModelCatalogItem } from '../types.js';

export const MODELS_CATALOG: ModelCatalogItem[] = [
  // 1. Modelos Estáveis (Produção / Texto Geral)
  {
    order: 1,
    id: 'gemini-3.8-flash',
    name: 'Gemini 3.8 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Modelo estável principal para raciocínio crítico, geração de texto geral, auditoria rigorosa de código e segurança.',
    recommendedRole: 'Auditor',
  },
  {
    order: 2,
    id: 'gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Raciocínio híbrido balanceado e diagnóstico investigativo detalhado com coleta de evidências.',
    recommendedRole: 'Investigator',
  },
  {
    order: 3,
    id: 'gemini-3.6-flash',
    name: 'Gemini 3.6 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Decisões arquiteturais de software, design estrutural de sistemas, modularidade e desacoplamento.',
    recommendedRole: 'Architect',
  },
  {
    order: 4,
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Equilíbrio sólido entre geração de código, velocidade e operações de texto multimodais.',
  },
  {
    order: 5,
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Validação ágil de comportamentos, construção de suítes de testes automatizados e checagem de regressões.',
    recommendedRole: 'Tester',
  },
  {
    order: 6,
    id: 'gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    rpm: '0 / 150',
    tpm: '250K',
    rpd: '0 / 500',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Alta cadência de requisições, refatoração de boilerplate e execução contínua de tarefas repetitivas.',
    recommendedRole: 'Worker',
  },
  {
    order: 7,
    id: 'gemini-3.5-flash-lite',
    name: 'Gemini 3.5 Flash Lite',
    rpm: '1 / 1521',
    tpm: '250K',
    rpd: '1 / 500',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Coordenação geral, roteamento e maior teto de requisições por minuto disponível no sistema.',
    recommendedRole: 'Principal / Orchestrator',
  },
  {
    order: 8,
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Geração estável consolidada para produção com suporte amplo a ferramentas padrão.',
  },
  {
    order: 9,
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash Lite',
    rpm: '0 / 100',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Versão ultra-leve para processamento rápido, baixa latência e menor overhead.',
  },
  {
    order: 10,
    id: 'gemini-flash-latest',
    name: 'Gemini Flash (Latest)',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Estável',
    group: 'stable',
    groupName: '1. Modelos Estáveis',
    description: 'Alias dinâmico que aponta automaticamente para a versão estável mais recente do Gemini Flash.',
  },

  // 2. Modelos Preview (Raciocínio Avançado, Imagem, Vídeo, Música e Robótica)
  {
    order: 1,
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro Preview',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Preview',
    group: 'preview',
    groupName: '2. Modelos Preview',
    subFunction: 'Raciocínio complexo & STEM',
    description: 'Raciocínio avançado, matemática, STEM, arquiteturas complexas e geração densa de código (Requer Chave Paga/AI Studio UI).',
  },
  {
    order: 2,
    id: 'gemini-3.1-flash-image',
    name: 'Gemini 3.1 Flash Image (Nano Banana 2)',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Preview',
    group: 'preview',
    groupName: '2. Modelos Preview',
    subFunction: 'Geração e edição de imagens em alta definição (até 4K)',
    description: 'Geração e edição de imagens em alta fidelidade com resoluções 512px, 1K, 2K e 4K, e suporte a busca web no Google Search.',
  },
  {
    order: 3,
    id: 'gemini-3.1-flash-lite-image',
    name: 'Gemini 3.1 Flash Lite Image (Nano Banana Lite)',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Preview',
    group: 'preview',
    groupName: '2. Modelos Preview',
    subFunction: 'Geração rápida de imagens',
    description: 'Geração rápida e econômica de imagens e edição visual multimodal.',
  },
  {
    order: 4,
    id: 'gemini-3-pro-image',
    name: 'Gemini 3 Pro Image (Nano Banana Pro)',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Preview',
    group: 'preview',
    groupName: '2. Modelos Preview',
    subFunction: 'Geração profissional de imagens',
    description: 'Geração de imagens de nível profissional com suporte a múltiplas proporções e busca no Google.',
  },
  {
    order: 5,
    id: 'veo-3.1-generate-preview',
    name: 'Veo 3.1 Generate Preview',
    rpm: '0 / 10',
    tpm: '50K',
    rpd: '0 / 10',
    category: 'Preview',
    group: 'preview',
    groupName: '2. Modelos Preview',
    subFunction: 'Geração de vídeo de alta resolução (1080p / 4K)',
    description: 'Geração de vídeo em alta qualidade com suporte a imagens de referência e extensão de clipes de vídeo.',
  },
  {
    order: 6,
    id: 'veo-3.1-lite-generate-preview',
    name: 'Veo 3.1 Lite Generate Preview',
    rpm: '0 / 20',
    tpm: '50K',
    rpd: '0 / 20',
    category: 'Preview',
    group: 'preview',
    groupName: '2. Modelos Preview',
    subFunction: 'Geração rápida de vídeo (720p / 1080p)',
    description: 'Geração ágil de vídeos curtos a partir de prompts de texto e imagens de início/fim.',
  },
  {
    order: 7,
    id: 'lyria-3-clip-preview',
    name: 'Lyria 3 Clip Preview',
    rpm: '0 / 20',
    tpm: '50K',
    rpd: '0 / 20',
    category: 'Preview',
    group: 'preview',
    groupName: '2. Modelos Preview',
    subFunction: 'Geração de clipes musicais curtos (até 30s)',
    description: 'Geração musical a partir de prompts de texto e imagens, retornando áudio WAV e letras sincronizadas.',
  },
  {
    order: 8,
    id: 'lyria-3-pro-preview',
    name: 'Lyria 3 Pro Preview',
    rpm: '0 / 10',
    tpm: '50K',
    rpd: '0 / 10',
    category: 'Preview',
    group: 'preview',
    groupName: '2. Modelos Preview',
    subFunction: 'Geração de faixas musicais completas',
    description: 'Composição musical completa de alta fidelidade para faixas instrumentais e vocais.',
  },
  {
    order: 9,
    id: 'gemini-robotics-er-2-preview',
    name: 'Gemini Robotics ER 2 Preview',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Preview',
    group: 'preview',
    groupName: '2. Modelos Preview',
    subFunction: 'Embodied AI e controle robótico espacial',
    description: 'Modelo especializado para tarefas espaciais, raciocínio embodied e visão computacional aplicada à robótica.',
  },

  // 3. Áudio, Voz e API Live
  {
    order: 1,
    id: 'gemini-3.5-transcribe',
    name: 'Gemini 3.5 Transcribe',
    rpm: '1 / 36',
    tpm: '10K',
    rpd: '1 / 255',
    category: 'Áudio',
    group: 'audio',
    groupName: '3. Áudio, Voz e API Live',
    subFunction: 'Transcrição STT (fala → texto estático)',
    description: 'Motor oficial de Speech-to-Text (STT) para transcrição de áudios pré-gravados e ditado via generateContent.',
  },
  {
    order: 2,
    id: 'gemini-3.1-flash-tts-preview',
    name: 'Gemini 3.1 Flash TTS Preview',
    rpm: '0 / 30',
    tpm: '10K',
    rpd: '0 / 106',
    category: 'Áudio',
    group: 'audio',
    groupName: '3. Áudio, Voz e API Live',
    subFunction: 'Síntese de voz TTS (texto → fala)',
    description: 'Síntese de voz natural de alta fidelidade mono e multi-locutor com vozes oficiais (Kore, Puck, Charon, Fenrir, Zephyr).',
  },
  {
    order: 3,
    id: 'gemini-3.8-live',
    name: 'Gemini 3.8 Live',
    rpm: '0 / Inf',
    tpm: '0 / 65K',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '3. Áudio, Voz e API Live',
    subFunction: 'Conversação de áudio/vídeo em tempo real (Live API)',
    description: 'Sessão contínua bidirecional de streaming de áudio e vídeo com baixíssima latência via WebSocket.',
  },
  {
    order: 4,
    id: 'gemini-3.8-live-extended-thinking',
    name: 'Gemini 3.8 Live Extended Thinking',
    rpm: '0 / Inf',
    tpm: '0 / 65K',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '3. Áudio, Voz e API Live',
    subFunction: 'Voz em tempo real com raciocínio estendido',
    description: 'Diálogo por voz em tempo real combinado com capacidade de raciocínio profundo e chamadas de ferramentas complexas.',
  },
  {
    order: 5,
    id: 'gemini-3.5-transcribe-live',
    name: 'Gemini 3.5 Transcribe Live',
    rpm: '0 / Inf',
    tpm: '0 / 20K',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '3. Áudio, Voz e API Live',
    subFunction: 'Transcrição e tradução de voz ao vivo (Live API)',
    description: 'Streaming contínuo para transcrição ao vivo e tradução simultânea de voz em múltiplos idiomas via Live API.',
  },

  // 4. Embeddings & Busca Semântica
  {
    order: 1,
    id: 'gemini-embedding-2-preview',
    name: 'Gemini Embedding 2 Preview',
    rpm: '0 / 1000',
    tpm: '30K',
    rpd: '0 / 1K',
    category: 'Embeddings',
    group: 'embeddings',
    groupName: '4. Embeddings & Busca Semântica',
    subFunction: 'Vetores densos de última geração',
    description: 'Embeddings modernos de alta densidade semântica para indexação de código, recuperação RAG e busca semântica.',
  },
  {
    order: 2,
    id: 'text-embedding-004',
    name: 'Text Embedding 004',
    rpm: '0 / 1000',
    tpm: '30K',
    rpd: '0 / 1K',
    category: 'Embeddings',
    group: 'embeddings',
    groupName: '4. Embeddings & Busca Semântica',
    subFunction: 'Vetores semânticos padrão de produção',
    description: 'Modelo estável e eficiente de embeddings para cálculo de similaridade textual e busca vetorial.',
  },

  // 5. Agentes & Automação
  {
    order: 1,
    id: 'antigravity',
    name: 'Antigravity Agent',
    rpm: '0 / 600',
    tpm: '100K',
    rpd: '0 / 100',
    category: 'Agents',
    group: 'agents',
    groupName: '5. Agentes & Automação',
    subFunction: 'Motor nativo dedicado para Agents autônomos',
    description: 'Motor oficial para agentes autônomos, execução contínua de tarefas, chamadas de ferramentas e desenvolvimento guiado.',
  },
  {
    order: 2,
    id: 'deep-research',
    name: 'Deep Research Agent',
    rpm: '0 / 60',
    tpm: '50K',
    rpd: '0 / 50',
    category: 'Agents',
    group: 'agents',
    groupName: '5. Agentes & Automação',
    subFunction: 'Agente de pesquisa profunda multi-etapa',
    description: 'Agente autônomo especializado em investigações analíticas aprofundadas, navegação multi-fonte e síntese estruturada.',
  },

  // 6. Modelos Abertos (Gemma)
  {
    order: 1,
    id: 'gemma-4-31b',
    name: 'Gemma 4 31B',
    rpm: '0 / 300',
    tpm: '16K',
    rpd: '0 / 14.4K',
    category: 'Gemma',
    group: 'gemma',
    groupName: '6. Modelos Abertos Gemma',
    subFunction: 'Modelo aberto de alta densidade (31B)',
    description: 'Família aberta Gemma 4 para execução descentralizada, auditoria de segurança e inferência local de alta capacidade.',
  },
  {
    order: 2,
    id: 'gemma-4-26b',
    name: 'Gemma 4 26B',
    rpm: '0 / 300',
    tpm: '16K',
    rpd: '0 / 14.4K',
    category: 'Gemma',
    group: 'gemma',
    groupName: '6. Modelos Abertos Gemma',
    subFunction: 'Modelo aberto balanceado (26B)',
    description: 'Família aberta Gemma 4 balanceada para tarefas pontuais de desenvolvimento e inferência com baixo consumo de memória.',
  },
];
