import { ModelCatalogItem } from '../types.js';

export const MODELS_CATALOG: ModelCatalogItem[] = [
  // 1. Texto, chat, raciocínio e geração textual
  {
    order: 1,
    id: 'gemini-3.8-flash',
    name: 'Gemini 3.8 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'stable',
    groupName: '1. Texto, chat, raciocínio e geração textual',
    description: 'Modelo estável principal para raciocínio crítico, geração de texto geral, auditoria de código e segurança.',
    recommendedRole: 'Auditor',
  },
  {
    order: 2,
    id: 'gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'stable',
    groupName: '1. Texto, chat, raciocínio e geração textual',
    description: 'Raciocínio híbrido balanceado e diagnóstico investigativo detalhado com coleta de evidências.',
    recommendedRole: 'Investigator',
  },
  {
    order: 3,
    id: 'gemini-3.6-flash',
    name: 'Gemini 3.6 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'stable',
    groupName: '1. Texto, chat, raciocínio e geração textual',
    description: 'Decisões arquiteturais de software, design estrutural de sistemas, modularidade e desacoplamento.',
    recommendedRole: 'Architect',
  },
  {
    order: 4,
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'stable',
    groupName: '1. Texto, chat, raciocínio e geração textual',
    description: 'Equilíbrio sólido entre geração de código, velocidade e operações de texto multimodais.',
  },
  {
    order: 5,
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'stable',
    groupName: '1. Texto, chat, raciocínio e geração textual',
    description: 'Validação ágil de comportamentos, construção de suítes de testes automatizados e checagem de regressões.',
    recommendedRole: 'Tester',
  },
  {
    order: 6,
    id: 'gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    rpm: '0 / 150',
    tpm: '250K',
    rpd: '0 / 500',
    category: 'Txt Out',
    group: 'stable',
    groupName: '1. Texto, chat, raciocínio e geração textual',
    description: 'Alta cadência de requisições, refatoração de boilerplate e execução contínua de tarefas repetitivas.',
    recommendedRole: 'Worker',
  },
  {
    order: 7,
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'stable',
    groupName: '1. Texto, chat, raciocínio e geração textual',
    description: 'Geração estável consolidada para produção com suporte amplo a ferramentas padrão.',
  },
  {
    order: 8,
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash Lite',
    rpm: '0 / 100',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'stable',
    groupName: '1. Texto, chat, raciocínio e geração textual',
    description: 'Versão ultra-leve para processamento rápido, baixa latência e menor overhead.',
  },
  {
    order: 9,
    id: 'gemini-3.5-flash-lite',
    name: 'Gemini 3.5 Flash Lite',
    rpm: '1 / 1521',
    tpm: '250K',
    rpd: '1 / 500',
    category: 'Txt Out',
    group: 'stable',
    groupName: '1. Texto, chat, raciocínio e geração textual',
    description: 'Coordenação geral, roteamento e maior teto de requisições por minuto disponível no sistema.',
    recommendedRole: 'Principal / Orchestrator',
  },

  // 2. Voz, transcrição, tradução e áudio em tempo real
  {
    order: 1,
    id: 'gemini-3.5-transcribe-live',
    name: 'Gemini 3.5 Transcribe Live',
    rpm: '0 / Inf',
    tpm: '0 / 20K',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Transcrição e tradução de voz ao vivo (Live API)',
    description: 'Streaming contínuo para transcrição ao vivo e tradução simultânea de voz em múltiplos idiomas via Live API.',
  },
  {
    order: 2,
    id: 'gemini-3.5-live-translate',
    name: 'Gemini 3.5 Live Translate',
    rpm: '0 / Inf',
    tpm: '0 / 20K',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Tradução de voz em tempo real contínua',
    description: 'Tradução simultânea bidirecional de voz em múltiplos idiomas em tempo real via Live API.',
  },
  {
    order: 3,
    id: 'gemini-3-flash-live',
    name: 'Gemini 3 Flash Live',
    rpm: '0 / Inf',
    tpm: '0 / 65K',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Conversação de áudio contínua (Live API)',
    description: 'Sessão contínua bidirecional de streaming de áudio com baixíssima latência via WebSocket.',
  },
  {
    order: 4,
    id: 'gemini-3.5-transcribe',
    name: 'Gemini 3.5 Transcribe',
    rpm: '1 / 36',
    tpm: '10K',
    rpd: '1 / 255',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Transcrição STT (fala → texto estático)',
    description: 'Motor oficial de Speech-to-Text (STT) para transcrição de áudios pré-gravados e ditado via generateContent.',
  },
  {
    order: 5,
    id: 'gemini-3.1-flash-tts',
    name: 'Gemini 3.1 Flash TTS',
    rpm: '0 / 30',
    tpm: '10K',
    rpd: '0 / 106',
    category: 'Multimod',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Síntese de voz TTS (texto → fala)',
    description: 'Síntese de voz natural de alta fidelidade mono e multi-locutor com vozes oficiais do sistema.',
  },
  {
    order: 6,
    id: 'gemini-2.5-flash-native-audio-dialog',
    name: 'Gemini 2.5 Flash Native Audio Dialog',
    rpm: '0 / Inf',
    tpm: '1M',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Diálogo de áudio nativo em tempo real',
    description: 'Diálogo conversacional de áudio contínuo e nativo de alta fidelidade via WebSocket.',
  },
  {
    order: 7,
    id: 'gemini-2.5-flash-tts',
    name: 'Gemini 2.5 Flash TTS',
    rpm: '0 / 30',
    tpm: '10K',
    rpd: '0 / 10',
    category: 'Multimod',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Síntese de voz TTS eficiente',
    description: 'Geração rápida e eficiente de fala natural a partir de texto.',
  },
];
