import { VoiceOption, DirectorPreset, VoiceAgent, VoiceDirectorConfig } from './voiceTypes.js';

// Catalog of 30 Voices
export const GEMINI_30_VOICES: VoiceOption[] = [
  {
    id: 'Kore',
    name: 'Kore (Oficial)',
    gender: 'Feminino',
    baseGeminiVoice: 'Kore',
    description: 'Voz feminina equilibrada, clara e altamente versátil para apresentações e narrações.',
    recommendedStyles: ['Conversacional', 'Formal', 'Educativo'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Puck',
    name: 'Puck (Oficial)',
    gender: 'Masculino',
    baseGeminiVoice: 'Puck',
    description: 'Voz masculina energética, jovem e dinâmica, ideal para podcasts e conteúdos informais.',
    recommendedStyles: ['Conversacional', 'Entusiasmado', 'Épico'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Charon',
    name: 'Charon (Oficial)',
    gender: 'Masculino',
    baseGeminiVoice: 'Charon',
    description: 'Voz masculina encorpada e profunda, perfeita para trailers, mistério e documentários.',
    recommendedStyles: ['Dramático', 'Épico', 'Formal'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Fenrir',
    name: 'Fenrir (Oficial)',
    gender: 'Masculino',
    baseGeminiVoice: 'Fenrir',
    description: 'Voz masculina forte, firme e autoritária para discursos e narrativas intensas.',
    recommendedStyles: ['Épico', 'Dramático', 'Urgente/Notícias'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Zephyr',
    name: 'Zephyr (Oficial)',
    gender: 'Feminino',
    baseGeminiVoice: 'Zephyr',
    description: 'Voz feminina serena, aveludada e suave, excelente para meditação e ASMR.',
    recommendedStyles: ['Calmo', 'Íntimo/ASMR', 'Conversacional'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Aoede',
    name: 'Aoede',
    gender: 'Feminino',
    baseGeminiVoice: 'Kore',
    description: 'Expressiva e melódica, excelente para contação de histórias e audiolivros.',
    recommendedStyles: ['Conversacional', 'Dramático'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Calliope',
    name: 'Calliope',
    gender: 'Feminino',
    baseGeminiVoice: 'Zephyr',
    description: 'Sofisticada e elegante, ideal para apresentações corporativas e marcas de luxo.',
    recommendedStyles: ['Formal', 'Calmo'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Orion',
    name: 'Orion',
    gender: 'Masculino',
    baseGeminiVoice: 'Puck',
    description: 'Voz masculina corporativa limpa, articulada para relatórios e tutoriais.',
    recommendedStyles: ['Educativo', 'Formal'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Pegasus',
    name: 'Pegasus',
    gender: 'Masculino',
    baseGeminiVoice: 'Fenrir',
    description: 'Cadência acelerada e marcante para boletins de notícias e resumos rápidos.',
    recommendedStyles: ['Urgente/Notícias', 'Sensacionalista'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Lyra',
    name: 'Lyra',
    gender: 'Feminino',
    baseGeminiVoice: 'Kore',
    description: 'Tom jovem, amigável e descontraído para redes sociais e vlogs.',
    recommendedStyles: ['Conversacional', 'Entusiasmado'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Atlas',
    name: 'Atlas',
    gender: 'Masculino',
    baseGeminiVoice: 'Charon',
    description: 'Ressoante e cinematográfica, desenvolvida para chamadas de ação marcantes.',
    recommendedStyles: ['Épico', 'Dramático'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Nova',
    name: 'Nova',
    gender: 'Feminino',
    baseGeminiVoice: 'Zephyr',
    description: 'Tom moderno e acolhedor para podcasts de entrevistas e tecnologia.',
    recommendedStyles: ['Conversacional', 'Educativo'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Echo',
    name: 'Echo',
    gender: 'Masculino',
    baseGeminiVoice: 'Charon',
    description: 'Intimista e pausado para narrativas reflexivas e documentários históricos.',
    recommendedStyles: ['Calmo', 'Dramático'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Astra',
    name: 'Astra',
    gender: 'Feminino',
    baseGeminiVoice: 'Kore',
    description: 'Tom pedagógico e didático para instruções de cursos e voz de assistente.',
    recommendedStyles: ['Educativo', 'Formal'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Chronos',
    name: 'Chronos',
    gender: 'Masculino',
    baseGeminiVoice: 'Charon',
    description: 'Misterioso e envolvente com dicção pausada para ficção e mistério.',
    recommendedStyles: ['Dramático', 'Épico'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Freya',
    name: 'Freya',
    gender: 'Feminino',
    baseGeminiVoice: 'Zephyr',
    description: 'Calorosa, empática e acolhedora para mensagens institucionais e saúde.',
    recommendedStyles: ['Calmo', 'Conversacional'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Helios',
    name: 'Helios',
    gender: 'Masculino',
    baseGeminiVoice: 'Puck',
    description: 'Vibrante, comercial e persuasivo para anúncios e campanhas de vendas.',
    recommendedStyles: ['Entusiasmado', 'Sensacionalista'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Iris',
    name: 'Iris',
    gender: 'Feminino',
    baseGeminiVoice: 'Kore',
    description: 'Dicção perfeita e tom neutro de âncora de telejornal de horário nobre.',
    recommendedStyles: ['Urgente/Notícias', 'Formal'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Titan',
    name: 'Titan',
    gender: 'Masculino',
    baseGeminiVoice: 'Fenrir',
    description: 'Impactante com graves acentuados para aberturas e trailers de jogos.',
    recommendedStyles: ['Épico', 'Dramático'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Minerva',
    name: 'Minerva',
    gender: 'Feminino',
    baseGeminiVoice: 'Zephyr',
    description: 'Voz sábia e ponderada para análises acadêmicas e audiolivros clássicos.',
    recommendedStyles: ['Formal', 'Educativo'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Apollo',
    name: 'Apollo',
    gender: 'Masculino',
    baseGeminiVoice: 'Puck',
    description: 'Entusiasta e multifacetado com modulação fluida e natural.',
    recommendedStyles: ['Conversacional', 'Educativo'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Selene',
    name: 'Selene',
    gender: 'Feminino',
    baseGeminiVoice: 'Zephyr',
    description: 'Aveludada e sussurrada para experiências imersivas de áudio relaxing.',
    recommendedStyles: ['Íntimo/ASMR', 'Calmo'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Vulcan',
    name: 'Vulcan',
    gender: 'Masculino',
    baseGeminiVoice: 'Fenrir',
    description: 'Enérgico para narrações esportivas e eventos ao vivo de alto ritmo.',
    recommendedStyles: ['Entusiasmado', 'Sensacionalista'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Maia',
    name: 'Maia',
    gender: 'Feminino',
    baseGeminiVoice: 'Kore',
    description: 'Descontraída e espontânea com entonações brasileiras modernas.',
    recommendedStyles: ['Conversacional', 'Entusiasmado'],
    nativeLanguage: 'pt-BR',
    accent: 'Nordestino (BR)',
  },
  {
    id: 'Hermes',
    name: 'Hermes',
    gender: 'Masculino',
    baseGeminiVoice: 'Puck',
    description: 'Informativo e dinâmico com acentuação carioca sutil.',
    recommendedStyles: ['Conversacional', 'Urgente/Notícias'],
    nativeLanguage: 'pt-BR',
    accent: 'Carioca (BR)',
  },
  {
    id: 'Hestia',
    name: 'Hestia',
    gender: 'Feminino',
    baseGeminiVoice: 'Zephyr',
    description: 'Serena e reflexiva com cadência pausada e respiração natural.',
    recommendedStyles: ['Calmo', 'Íntimo/ASMR'],
    nativeLanguage: 'pt-BR',
    accent: 'Sulista (BR)',
  },
  {
    id: 'Castor',
    name: 'Castor',
    gender: 'Masculino',
    baseGeminiVoice: 'Puck',
    description: 'Voz jovem e enérgica com estilo gamer e comunicação direta.',
    recommendedStyles: ['Entusiasmado', 'Conversacional'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Pollux',
    name: 'Pollux',
    gender: 'Masculino',
    baseGeminiVoice: 'Puck',
    description: 'Tom descontraído de estúdio para podcasts em formato de bate-papo.',
    recommendedStyles: ['Conversacional', 'Calmo'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Nyx',
    name: 'Nyx',
    gender: 'Feminino',
    baseGeminiVoice: 'Charon',
    description: 'Voz sombria, enigmática e profunda para suspense e terror.',
    recommendedStyles: ['Dramático', 'Épico'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
  {
    id: 'Sol',
    name: 'Sol',
    gender: 'Masculino',
    baseGeminiVoice: 'Puck',
    description: 'Brilhante e inspiradora para palestras motivacionais e resumos.',
    recommendedStyles: ['Entusiasmado', 'Educativo'],
    nativeLanguage: 'pt-BR',
    accent: 'Neutro/Sudoeste (BR)',
  },
];

// 14 Director Presets
export const VOICE_DIRECTOR_PRESETS: DirectorPreset[] = [
  {
    id: 'preset_cinematic',
    name: 'Narrador Cinematográfico',
    category: 'Cinematográfico',
    description: 'Voz encorpada, presença marcante, pausas dramáticas e ressonância grave.',
    iconName: 'Clapperboard',
    config: {
      voiceId: 'Charon',
      baseGeminiVoice: 'Charon',
      style: 'Dramático',
      emotion: 'Sério',
      tone: 'Grave',
      rhythm: 'Pausado/Lento',
      expressiveness: 'Intenso',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Dramáticas/Extensas',
      pitch: -3,
      speed: 0.9,
    },
  },
  {
    id: 'preset_documentary',
    name: 'Documentário Nacional',
    category: 'Mídia & Notícias',
    description: 'Tom contemplativo, sóbrio, bem articulado e focado no conteúdo reflexivo.',
    iconName: 'Film',
    config: {
      voiceId: 'Minerva',
      baseGeminiVoice: 'Zephyr',
      style: 'Formal',
      emotion: 'Empático',
      tone: 'Acolhedor',
      rhythm: 'Fluído/Natural',
      expressiveness: 'Moderado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Pontuadas',
      pitch: -1,
      speed: 0.95,
    },
  },
  {
    id: 'preset_storyteller',
    name: 'Storyteller Imersivo',
    category: 'Cinematográfico',
    description: 'Rico em variações de entonação, transportando o ouvinte para a história.',
    iconName: 'BookOpen',
    config: {
      voiceId: 'Aoede',
      baseGeminiVoice: 'Kore',
      style: 'Conversacional',
      emotion: 'Curioso',
      tone: 'Grave',
      rhythm: 'Poético',
      expressiveness: 'Intenso',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Naturais',
      pitch: 0,
      speed: 1.0,
    },
  },
  {
    id: 'preset_trailer',
    name: 'Trailer Épico',
    category: 'Cinematográfico',
    description: 'Impacto total, tom potente, grave rimbombante e projeção máxima.',
    iconName: 'Zap',
    config: {
      voiceId: 'Titan',
      baseGeminiVoice: 'Fenrir',
      style: 'Épico',
      emotion: 'Bravo/Autoritário',
      tone: 'Impositivo',
      rhythm: 'Rítmico',
      expressiveness: 'Exagerado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Dramáticas/Extensas',
      pitch: -5,
      speed: 0.85,
    },
  },
  {
    id: 'preset_news',
    name: 'Noticiário Prime Time',
    category: 'Mídia & Notícias',
    description: 'Articulação impecável, tom neutro, urgência calibrada e fluidez de ancoragem.',
    iconName: 'Newspaper',
    config: {
      voiceId: 'Iris',
      baseGeminiVoice: 'Kore',
      style: 'Urgente/Notícias',
      emotion: 'Sério',
      tone: 'Corporativo',
      rhythm: 'Telejornalístico',
      expressiveness: 'Moderado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Pontuadas',
      pitch: 0,
      speed: 1.05,
    },
  },
  {
    id: 'preset_podcast',
    name: 'Host de Podcast',
    category: 'Conversacional',
    description: 'Descontraído, próximo do ouvinte, ritmo orgânico e naturalidade fluida.',
    iconName: 'Mic',
    config: {
      voiceId: 'Puck',
      baseGeminiVoice: 'Puck',
      style: 'Conversacional',
      emotion: 'Amigável',
      tone: 'Acolhedor',
      rhythm: 'Fluído/Natural',
      expressiveness: 'Moderado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Naturais',
      pitch: 1,
      speed: 1.0,
    },
  },
  {
    id: 'preset_conversational',
    name: 'Conversacional Amigável',
    category: 'Conversacional',
    description: 'Voz humana cotidiana, tom leve, receptivo e agradável para diálogos.',
    iconName: 'MessageSquare',
    config: {
      voiceId: 'Kore',
      baseGeminiVoice: 'Kore',
      style: 'Conversacional',
      emotion: 'Alegre',
      tone: 'Acolhedor',
      rhythm: 'Fluído/Natural',
      expressiveness: 'Moderado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Naturais',
      pitch: 0,
      speed: 1.0,
    },
  },
  {
    id: 'preset_tutorial',
    name: 'Tutorial & Instrução',
    category: 'Especializado',
    description: 'Clareza didática, ritmo moderado, facilidade de compreensão e paciência.',
    iconName: 'GraduationCap',
    config: {
      voiceId: 'Astra',
      baseGeminiVoice: 'Kore',
      style: 'Educativo',
      emotion: 'Confiante',
      tone: 'Corporativo',
      rhythm: 'Pausado/Lento',
      expressiveness: 'Sutil',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Pontuadas',
      pitch: 0,
      speed: 0.95,
    },
  },
  {
    id: 'preset_asmr',
    name: 'ASMR & Meditação',
    category: 'Especializado',
    description: 'Projeção sussurrada, calma profunda, redução de picos e tom hipnótico.',
    iconName: 'Feather',
    config: {
      voiceId: 'Selene',
      baseGeminiVoice: 'Zephyr',
      style: 'Íntimo/ASMR',
      emotion: 'Empático',
      tone: 'Suave',
      rhythm: 'Pausado/Lento',
      expressiveness: 'Sutil',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Dramáticas/Extensas',
      pitch: 2,
      speed: 0.8,
    },
  },
  {
    id: 'preset_dramatic',
    name: 'Dramático Emocional',
    category: 'Entretenimento',
    description: 'Carga emocional elevada, suspiros, cadência desacelerada e intensidade.',
    iconName: 'Flame',
    config: {
      voiceId: 'Charon',
      baseGeminiVoice: 'Charon',
      style: 'Dramático',
      emotion: 'Triste',
      tone: 'Grave',
      rhythm: 'Poético',
      expressiveness: 'Intenso',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Dramáticas/Extensas',
      pitch: -2,
      speed: 0.88,
    },
  },
  {
    id: 'preset_mysterious',
    name: 'Misterioso & Sombrio',
    category: 'Entretenimento',
    description: 'Sussurros graves, ritmo pausado, criando tensão e suspense constante.',
    iconName: 'Ghost',
    config: {
      voiceId: 'Nyx',
      baseGeminiVoice: 'Charon',
      style: 'Dramático',
      emotion: 'Misterioso',
      tone: 'Grave',
      rhythm: 'Pausado/Lento',
      expressiveness: 'Intenso',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Dramáticas/Extensas',
      pitch: -4,
      speed: 0.85,
    },
  },
  {
    id: 'preset_energetic',
    name: 'Energético & Gamer',
    category: 'Entretenimento',
    description: 'Projeção lábil, alta velocidade, vibração constante e tom empolgado.',
    iconName: 'Radio',
    config: {
      voiceId: 'Castor',
      baseGeminiVoice: 'Puck',
      style: 'Entusiasmado',
      emotion: 'Alegre',
      tone: 'Provocativo',
      rhythm: 'Acelerado/Dinâmico',
      expressiveness: 'Exagerado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Mínimas',
      pitch: 3,
      speed: 1.15,
    },
  },
  {
    id: 'preset_natural_live',
    name: 'Live & Espontâneo',
    category: 'Conversacional',
    description: 'Leves hesitações humanas naturais, tom caloroso e conexão direta.',
    iconName: 'Wifi',
    config: {
      voiceId: 'Maia',
      baseGeminiVoice: 'Kore',
      style: 'Conversacional',
      emotion: 'Amigável',
      tone: 'Acolhedor',
      rhythm: 'Fluído/Natural',
      expressiveness: 'Moderado',
      accent: 'Nordestino (BR)',
      pauseStyle: 'Naturais',
      pitch: 0,
      speed: 1.0,
    },
  },
  {
    id: 'preset_custom',
    name: 'Personalizado / Estúdio Livre',
    category: 'Especializado',
    description: 'Controle manual total sobre todos os knobs, velocidade, sotaque e afinação.',
    iconName: 'Sliders',
    config: {
      voiceId: 'Kore',
      baseGeminiVoice: 'Kore',
      style: 'Conversacional',
      emotion: 'Neutro',
      tone: 'Médio',
      rhythm: 'Fluído/Natural',
      expressiveness: 'Moderado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Naturais',
      pitch: 0,
      speed: 1.0,
    },
  },
];

// In-Text Performance Markup Tags (Injected at cursor in input/textarea)
export const PERFORMANCE_MARKUP_TAGS = [
  { label: 'Pausa Curta', tag: '[pausa curta]', desc: 'Adiciona ~0.5s de silêncio', icon: 'Pause' },
  { label: 'Pausa Média', tag: '[pausa media]', desc: 'Adiciona ~1.0s de silêncio', icon: 'Pause' },
  { label: 'Pausa Longa', tag: '[pausa longa]', desc: 'Adiciona ~2.0s de silêncio dramático', icon: 'PauseOctagon' },
  { label: 'Sussurro', tag: '[sussurrando]', desc: 'Modula o trecho para tom confidencial', icon: 'VolumeX' },
  { label: 'Grito / Enfático', tag: '[gritando]', desc: 'Aumenta projeção e volume vocal', icon: 'Volume2' },
  { label: 'Suspiro', tag: '[suspiro]', desc: 'Abre trecho com suspiro audível', icon: 'Wind' },
  { label: 'Risada / Risos', tag: '[risos]', desc: 'Gera risadinha leve antes da frase', icon: 'Smile' },
  { label: 'Hesitação / Uhm', tag: '[uhm]', desc: 'Simula momento de pensamento humano', icon: 'HelpCircle' },
  { label: 'Sarcasmo', tag: '[sarcástico]', desc: 'Adiciona ironia na entonação', icon: 'Zap' },
  { label: 'Ênfase', tag: '[ênfase]', desc: 'Destaca a pronúncia das palavras', icon: 'Sparkles' },
  { label: 'Pigarro', tag: '[pigarreado]', desc: 'Pausa para limpar a garganta', icon: 'Activity' },
  { label: 'Arquejo', tag: '[ofegante]', desc: 'Simula respiração acelerada', icon: 'HeartPulse' },
];

// Factory Default Voice Agents
export const FACTORY_VOICE_AGENTS: VoiceAgent[] = [
  {
    id: 'agent_narrador_oficial',
    name: 'Meu Narrador Principal',
    description: 'Agente de voz padrão para leitura corporativa e respostas do assistente.',
    type: 'narrator',
    config: {
      voiceId: 'Kore',
      baseGeminiVoice: 'Kore',
      model: 'gemini-3.5-flash-lite',
      language: 'pt-BR',
      style: 'Conversacional',
      emotion: 'Amigável',
      tone: 'Acolhedor',
      rhythm: 'Fluído/Natural',
      expressiveness: 'Moderado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Naturais',
      pitch: 0,
      volume: 100,
      speed: 1.0,
      presetName: 'Narrador Principal',
    },
    directorPrompt:
      'Direção Vocal: Narre de forma clara, amigável e profissional. Mantenha dicção neutra brasileira com tom acolhedor.',
    sttInstructions:
      'Transcreva o áudio com precisão absoluta, mantendo termos em inglês e formatando com pontuação correta.',
    isSystemDefaultTts: true,
    isSystemDefaultStt: true,
    createdAt: Date.now() - 100000,
    updatedAt: Date.now() - 100000,
  },
  {
    id: 'agent_voz_doc',
    name: 'Voz Documentário',
    description: 'Apresentador sóbrio para explicações técnicas densas e artigos.',
    type: 'narrator',
    config: {
      voiceId: 'Minerva',
      baseGeminiVoice: 'Zephyr',
      model: 'gemini-3.5-flash-lite',
      language: 'pt-BR',
      style: 'Formal',
      emotion: 'Sério',
      tone: 'Grave',
      rhythm: 'Pausado/Lento',
      expressiveness: 'Moderado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Pontuadas',
      pitch: -2,
      volume: 100,
      speed: 0.9,
      presetName: 'Documentário Nacional',
    },
    directorPrompt:
      'Direção Vocal: Estilo de narração de documentário da BBC/National Geographic. Voz grave, pausa deliberada e dicção perfeita.',
    isSystemDefaultTts: false,
    isSystemDefaultStt: false,
    createdAt: Date.now() - 80000,
    updatedAt: Date.now() - 80000,
  },
  {
    id: 'agent_trailer_epic',
    name: 'Trailer Épico',
    description: 'Direção pesada com impacto máximo de estúdio de cinema.',
    type: 'narrator',
    config: {
      voiceId: 'Titan',
      baseGeminiVoice: 'Fenrir',
      model: 'gemini-3.5-flash-lite',
      language: 'pt-BR',
      style: 'Épico',
      emotion: 'Bravo/Autoritário',
      tone: 'Impositivo',
      rhythm: 'Rítmico',
      expressiveness: 'Exagerado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Dramáticas/Extensas',
      pitch: -5,
      volume: 100,
      speed: 0.85,
      presetName: 'Trailer Épico',
    },
    directorPrompt:
      'Direção Vocal: Locução de trailer cinematográfico Hollywoodiano. Voz muito grave, impositiva, com autoridade e ressonância máxima.',
    isSystemDefaultTts: false,
    isSystemDefaultStt: false,
    createdAt: Date.now() - 60000,
    updatedAt: Date.now() - 60000,
  },
  {
    id: 'agent_live_natural',
    name: 'Live Natural',
    description: 'Locução leve e conversacional para transmissões e resumos.',
    type: 'narrator',
    config: {
      voiceId: 'Maia',
      baseGeminiVoice: 'Kore',
      model: 'gemini-3.5-flash-lite',
      language: 'pt-BR',
      style: 'Conversacional',
      emotion: 'Alegre',
      tone: 'Acolhedor',
      rhythm: 'Fluído/Natural',
      expressiveness: 'Moderado',
      accent: 'Nordestino (BR)',
      pauseStyle: 'Naturais',
      pitch: 0,
      volume: 100,
      speed: 1.0,
      presetName: 'Live & Espontâneo',
    },
    directorPrompt:
      'Direção Vocal: Fala totalmente natural, leve e espontânea como em uma transmissão ao vivo com amigos.',
    isSystemDefaultTts: false,
    isSystemDefaultStt: false,
    createdAt: Date.now() - 40000,
    updatedAt: Date.now() - 40000,
  },
  {
    id: 'agent_apresentador',
    name: 'Apresentador de Notícias',
    description: 'Âncora de telejornal de grande rede nacional.',
    type: 'narrator',
    config: {
      voiceId: 'Iris',
      baseGeminiVoice: 'Kore',
      model: 'gemini-3.5-flash-lite',
      language: 'pt-BR',
      style: 'Urgente/Notícias',
      emotion: 'Sério',
      tone: 'Corporativo',
      rhythm: 'Telejornalístico',
      expressiveness: 'Moderado',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Pontuadas',
      pitch: 0,
      volume: 100,
      speed: 1.05,
      presetName: 'Noticiário Prime Time',
    },
    directorPrompt:
      'Direção Vocal: Ancoragem de notícias de televisão. Ritmo firme, seguro, perfeitamente pontuado e profissional.',
    isSystemDefaultTts: false,
    isSystemDefaultStt: false,
    createdAt: Date.now() - 20000,
    updatedAt: Date.now() - 20000,
  },
  {
    id: 'agent_storyteller',
    name: 'Contador de Histórias',
    description: 'Voz envolvente para fábulas, ficção e narração de RPG.',
    type: 'narrator',
    config: {
      voiceId: 'Aoede',
      baseGeminiVoice: 'Kore',
      model: 'gemini-3.5-flash-lite',
      language: 'pt-BR',
      style: 'Conversacional',
      emotion: 'Curioso',
      tone: 'Grave',
      rhythm: 'Poético',
      expressiveness: 'Intenso',
      accent: 'Neutro/Sudoeste (BR)',
      pauseStyle: 'Naturais',
      pitch: 0,
      volume: 100,
      speed: 0.95,
      presetName: 'Storyteller Imersivo',
    },
    directorPrompt:
      'Direção Vocal: Leitura narrativa rica em emoção, mistério e entusiasmo controlado. Mude a entonação conforme os acontecimentos.',
    isSystemDefaultTts: false,
    isSystemDefaultStt: false,
    createdAt: Date.now() - 10000,
    updatedAt: Date.now() - 10000,
  },
];
